
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tawfik
 */
public class prinform extends javax.swing.JFrame {

  
   
   praktikant pr =new praktikant();
    
    public prinform() {
        
        initComponents();
        ButtonGroup bg =new ButtonGroup();
        bg.add(jRadioButton_mannlich);
        bg.add(jRadioButton_weiblich);

        pr.display(table1);
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id_label1 = new javax.swing.JLabel();
        id_label2 = new javax.swing.JLabel();
        id_label3 = new javax.swing.JLabel();
        id_label4 = new javax.swing.JLabel();
        id_label5 = new javax.swing.JLabel();
        id_label6 = new javax.swing.JLabel();
        id_label7 = new javax.swing.JLabel();
        jTextField_nachname = new javax.swing.JTextField();
        jTextField_vorname = new javax.swing.JTextField();
        jTextField_daure = new javax.swing.JTextField();
        jRadioButton_mannlich = new javax.swing.JRadioButton();
        jRadioButton_weiblich = new javax.swing.JRadioButton();
        button_einfugen = new javax.swing.JButton();
        Button_cancel = new javax.swing.JButton();
        jDateChooser_datum = new com.toedter.calendar.JDateChooser();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_service = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        button_loschen = new javax.swing.JButton();
        button_bearbeiten = new javax.swing.JButton();
        jTextField_suchen = new javax.swing.JTextField();
        id_label8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1500, 1500));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Mangment Praktikant");

        id_label1.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label1.setText("Vorname");

        id_label2.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label2.setText("Service");

        id_label3.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label3.setText("Identifikationsnummer");

        id_label4.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label4.setText("Nachname");

        id_label5.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label5.setText("Geburtsdatum");

        id_label6.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label6.setText("Geschlecht");

        id_label7.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label7.setText("Dauer des Praktikums");

        jTextField_nachname.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        jTextField_vorname.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField_vorname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_vornameActionPerformed(evt);
            }
        });

        jTextField_daure.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N

        jRadioButton_mannlich.setBackground(java.awt.SystemColor.window);
        jRadioButton_mannlich.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jRadioButton_mannlich.setText("Männlich");

        jRadioButton_weiblich.setBackground(java.awt.SystemColor.window);
        jRadioButton_weiblich.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jRadioButton_weiblich.setText("Weiblich");
        jRadioButton_weiblich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_weiblichActionPerformed(evt);
            }
        });

        button_einfugen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_einfugen.setIcon(new javax.swing.ImageIcon("C:\\Users\\tawfik\\Desktop\\java\\ajouter.png")); // NOI18N
        button_einfugen.setText("Einfügen");
        button_einfugen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_einfugenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_einfugenMouseExited(evt);
            }
        });
        button_einfugen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_einfugenActionPerformed(evt);
            }
        });

        Button_cancel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Button_cancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\tawfik\\Desktop\\java\\actualiser .png")); // NOI18N
        Button_cancel.setText("Cancel");
        Button_cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button_cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button_cancelMouseExited(evt);
            }
        });
        Button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_cancelActionPerformed(evt);
            }
        });

        jTextField_ID.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_IDActionPerformed(evt);
            }
        });
        jTextField_ID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IDKeyTyped(evt);
            }
        });

        jTextField_service.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField_service.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_serviceActionPerformed(evt);
            }
        });

        table1.setForeground(new java.awt.Color(153, 153, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "identifikationsnumme", "Vorname", "Nachname", "GebursDatum", "Service", "Dauer von Praktukium", "Geschelcht"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setResizable(false);
        }

        button_loschen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_loschen.setIcon(new javax.swing.ImageIcon("C:\\Users\\tawfik\\Desktop\\java\\supprimer.png")); // NOI18N
        button_loschen.setText("Löschen");
        button_loschen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_loschenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_loschenMouseExited(evt);
            }
        });
        button_loschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loschenActionPerformed(evt);
            }
        });

        button_bearbeiten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        button_bearbeiten.setIcon(new javax.swing.ImageIcon("C:\\Users\\tawfik\\Desktop\\java\\modifier.png")); // NOI18N
        button_bearbeiten.setText("Bearbeiten");
        button_bearbeiten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button_bearbeitenMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button_bearbeitenMouseExited(evt);
            }
        });
        button_bearbeiten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bearbeitenActionPerformed(evt);
            }
        });

        jTextField_suchen.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jTextField_suchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_suchenActionPerformed(evt);
            }
        });
        jTextField_suchen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_suchenKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_suchenKeyTyped(evt);
            }
        });

        id_label8.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        id_label8.setText("Geben sie die Identifikationsnummer ein");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(471, 471, 471)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(252, 252, 252)
                                .addComponent(Button_cancel)
                                .addGap(31, 31, 31)
                                .addComponent(button_einfugen))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_label7, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(id_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_mannlich, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                                        .addComponent(jRadioButton_weiblich, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextField_ID)
                                    .addComponent(jTextField_vorname)
                                    .addComponent(jTextField_nachname)
                                    .addComponent(jDateChooser_datum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField_service)
                                    .addComponent(jTextField_daure))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(button_loschen)
                                .addGap(29, 29, 29)
                                .addComponent(button_bearbeiten))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addComponent(jTextField_suchen, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 795, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(133, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(93, 93, 93)
                    .addComponent(id_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1220, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(id_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_vorname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(id_label4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_nachname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(id_label5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(id_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_service, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jDateChooser_datum, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(id_label7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_daure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_label6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton_mannlich)
                            .addComponent(jRadioButton_weiblich))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_suchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_label8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_einfugen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Button_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_loschen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_bearbeiten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(id_label3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1347, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_serviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_serviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_serviceActionPerformed

    private void jTextField_IDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IDKeyTyped
        //Nur Ziffer in jTextField_ID
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_IDKeyTyped

    private void jTextField_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_IDActionPerformed

    private void button_einfugenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_einfugenActionPerformed

        
         if(verif())
           {
        int  id = Integer.valueOf(jTextField_ID.getText()); 
           
           String vorname =jTextField_vorname.getText() ;
           String nachname =jTextField_nachname.getText() ;
                   
          String service =jTextField_service.getText() ;
          String daure =jTextField_daure.getText() ;
         
           
                String gesch ="weiblich";
           if (jRadioButton_mannlich.isSelected())
                {
                    gesch ="männlich";
                }
                SimpleDateFormat dateformt = new SimpleDateFormat("yyyy-MM-dd");
                String Datum = dateformt.format(jDateChooser_datum.getDate());
                pr.Inser(id, vorname, nachname, Datum, service, daure, gesch);
                pr.display(table1);
                clear();
           }
           else
        {
            JOptionPane.showMessageDialog(null,"Sie müssen alle felder ausfüllen");
        }
               
        
    }//GEN-LAST:event_button_einfugenActionPerformed

    private void jRadioButton_weiblichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_weiblichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_weiblichActionPerformed

    private void jTextField_vornameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_vornameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_vornameActionPerformed

    private void button_loschenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loschenActionPerformed
       if(verifid())
           {
        int  id = Integer.valueOf(jTextField_ID.getText()); 
           
           
                pr.delete(id);
                pr.display(table1);
                clear();
           }
           else
        {
            JOptionPane.showMessageDialog(null,"Sie müssen die  felder identifikationsnummer eingeben");
        }
    }//GEN-LAST:event_button_loschenActionPerformed

    private void button_bearbeitenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bearbeitenActionPerformed
          
        if(verif())
           {
        int  id = Integer.valueOf(jTextField_ID.getText()); 
           
           String vorname =jTextField_vorname.getText() ;
           String nachname =jTextField_nachname.getText() ;
                   
          String service =jTextField_service.getText() ;
          String daure =jTextField_daure.getText() ;
         
           
                String gesch ="weiblich";
           if (jRadioButton_mannlich.isSelected())
                {
                    gesch ="männlich";
                }
                SimpleDateFormat dateformt = new SimpleDateFormat("yyyy-MM-dd");
                String Datum = dateformt.format(jDateChooser_datum.getDate());
                pr.update(id, vorname, nachname, Datum, service, daure, gesch);
                pr.display(table1);
                clear();
           }
           else
        {
            JOptionPane.showMessageDialog(null,"Sie müssen alle felder ausfüllen");
        }
               
               
    }//GEN-LAST:event_button_bearbeitenActionPerformed

    private void Button_cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_cancelMouseEntered
       Button_cancel.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_Button_cancelMouseEntered

    private void Button_cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_cancelMouseExited
              Button_cancel.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_Button_cancelMouseExited

    private void button_einfugenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_einfugenMouseEntered
        button_einfugen.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_button_einfugenMouseEntered

    private void button_loschenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loschenMouseEntered
      button_loschen.setBackground(new java.awt.Color(51,51,255));   
    }//GEN-LAST:event_button_loschenMouseEntered

    private void button_bearbeitenMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_bearbeitenMouseEntered
       button_bearbeiten.setBackground(new java.awt.Color(51,51,255));
    }//GEN-LAST:event_button_bearbeitenMouseEntered

    private void button_einfugenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_einfugenMouseExited
         button_einfugen.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_button_einfugenMouseExited

    private void button_loschenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_loschenMouseExited
       button_loschen.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_button_loschenMouseExited

    private void button_bearbeitenMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_bearbeitenMouseExited
        button_bearbeiten.setBackground(new java.awt.Color(240,240,240));
    }//GEN-LAST:event_button_bearbeitenMouseExited

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
    
   
    }//GEN-LAST:event_formWindowOpened

    private void table1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table1MouseClicked
       int rowindex=table1.getSelectedRow();
       DefaultTableModel md = (DefaultTableModel) table1.getModel();
       if(md.getValueAt(rowindex,6).toString().equals("männlich"))
       {
           jRadioButton_mannlich.setSelected(true);
           jRadioButton_weiblich.setSelected(false);
           
       }else
       {
           jRadioButton_mannlich.setSelected(false);
           jRadioButton_weiblich.setSelected(true);
       }
       jTextField_ID.setText(md.getValueAt(rowindex, 0).toString());
       jTextField_vorname.setText(md.getValueAt(rowindex, 1).toString());
       jTextField_nachname.setText(md.getValueAt(rowindex, 2).toString());
       jTextField_service.setText(md.getValueAt(rowindex, 4).toString());
       jTextField_daure.setText(md.getValueAt(rowindex, 5).toString());
       
       Date datum;
       try {
           datum =new SimpleDateFormat("yyyy-MM-dd").parse(md.getValueAt(rowindex,3).toString());
           jDateChooser_datum.setDate(datum);
       } catch (Exception e) {
           System.out.println(e);
       }
       
       
    }//GEN-LAST:event_table1MouseClicked

    private void jTextField_suchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_suchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_suchenActionPerformed

    private void jTextField_suchenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_suchenKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_suchenKeyTyped

    private void jTextField_suchenKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_suchenKeyReleased
    
        DefaultTableModel table =(DefaultTableModel)table1.getModel();
          String taw= jTextField_suchen.getText();
          TableRowSorter<DefaultTableModel>tr =new TableRowSorter<DefaultTableModel>(table);
          table1.setRowSorter(tr);
          tr.setRowFilter(RowFilter.regexFilter(taw));
    }//GEN-LAST:event_jTextField_suchenKeyReleased

    private void Button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_cancelActionPerformed
        clear();
    }//GEN-LAST:event_Button_cancelActionPerformed

    

    public  boolean verif()
    {
        
        if (jTextField_ID.getText().equals("")||jTextField_vorname.getText().equals("")||jTextField_nachname.getText().equals("")
                || jDateChooser_datum.getDate()== null || jTextField_service.getText().equals("")||jTextField_daure.getText().equals("")
                ||!(((jRadioButton_weiblich.isSelected()) ||(jRadioButton_mannlich.isSelected())))  )
        {
           
            return false;
        }
        else
        {
        return true;
        }
    }
    public void clear()
    {
        jTextField_ID.setText("");
        jTextField_vorname.setText("");
         jTextField_nachname.setText("");
         jTextField_service.setText("");
         jTextField_daure.setText("");
        jDateChooser_datum.setDate(null);
        jRadioButton_weiblich.setSelected(false) ;
        jRadioButton_mannlich.setSelected(false); 
        
           
        
        
    }
     public  boolean verifid()
    {
        
        if (jTextField_ID.getText().equals("")  )
        {
           
            return false;
        }
        else
        {
        return true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prinform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prinform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prinform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prinform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prinform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_cancel;
    private javax.swing.JButton button_bearbeiten;
    private javax.swing.JButton button_einfugen;
    private javax.swing.JButton button_loschen;
    private javax.swing.JLabel id_label1;
    private javax.swing.JLabel id_label2;
    private javax.swing.JLabel id_label3;
    private javax.swing.JLabel id_label4;
    private javax.swing.JLabel id_label5;
    private javax.swing.JLabel id_label6;
    private javax.swing.JLabel id_label7;
    private javax.swing.JLabel id_label8;
    private com.toedter.calendar.JDateChooser jDateChooser_datum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_mannlich;
    private javax.swing.JRadioButton jRadioButton_weiblich;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_daure;
    private javax.swing.JTextField jTextField_nachname;
    private javax.swing.JTextField jTextField_service;
    private javax.swing.JTextField jTextField_suchen;
    private javax.swing.JTextField jTextField_vorname;
    private javax.swing.JTable table1;
    // End of variables declaration//GEN-END:variables
}
